### PR TITLE
Had a couple of issues building and running this locally

### PR DESCRIPTION
**Pull request by oleorhagen**
Leaving this up here, not sure what is expected or not, so feel free to ignore.

### CODE REVIEW

**Comment by oleorhagen** [comment]
@andreasfertig

**Comment by andreasfertig** [comment]
Hello @oleorhagen,

thanks for the PR! Can you please elaborate on what issues you had?


Andreas

**Comment by oleorhagen** [comment]
Yes, of course.

Apologies, the PR did not come with a lot of information:

1. The build fails, as the architecture `arch` in `build.sh` is lowercase, and hence not set properly.
2. The naming of the container. It seems `insights-test` is expected. But it was currently named `insights-testtest`

**Comment by andreasfertig** [comment]
Hello @oleorhagen,

>     1. The build fails, as the architecture `arch` in `build.sh` is lowercase, and hence not set properly.

Correct. The required change seems to be the one in line 7. Adding `TARGETARCH` to `docker build` is unecessary. Docker takes care of that based on `--platform linux/${ARCH}`.

 
>     2. The naming of the container. It seems `insights-test` is expected. But it was currently named `insights-testtest`

`insights-testtest` is the correct name. I'm not sure which issues you hit here, but the tests in `test.sh` are based on that name.

I'm happy to merge the PR if you adjust it. In its current shape, the PR will break the C++ Insights web page or, hopefully, the GitHub Action build before that.

Andreas

**Comment by oleorhagen** [comment]
> Hello @oleorhagen,
> 
> > ```
> > 1. The build fails, as the architecture `arch` in `build.sh` is lowercase, and hence not set properly.
> > ```
> 
> Correct. The required change seems to be the one in line 7. Adding `TARGETARCH` to `docker build` is unecessary. 

Alright, removed

Docker takes care of that based on `--platform linux/${ARCH}`.
> 
> > ```
> > 2. The naming of the container. It seems `insights-test` is expected. But it was currently named `insights-testtest`
> > ```
> 
> `insights-testtest` is the correct name. I'm not sure which issues you hit here, but the tests in `test.sh` are based on that name.
> 

Ok, good :)

I've changed the name in the `run.sh` script to `insights-test-test` then

> I'm happy to merge the PR if you adjust it. In its current shape, the PR will break the C++ Insights web page or, hopefully, the GitHub Action build before that.
> 
> Andreas

**Comment by andreasfertig** [comment]
Sorry for the delay! Thanks for your contribution!

**Pull request merged**
